### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by JakeGinnivan** [sevenwestmedia-labs/nx-generators#4]
We have `@wanews/typescript-project-references` and `@wanews/nx-esbuild`

## @wanews/typescript-project-references

Has the generator which converts an NX project, and a `package` executor which will package a library for NPM publish (using tsup atm).

## @wanews/nx-esbuild

Has a generator to create a node project, and executors to build (for prod) and serve (for local dev) that node project.

## Next up

* Generator to create a library
* Generator to create a Pulumi project for another project - this will allow serverless mono to have an infrastructure project for each of it's apps. ie `corporate-subs-dash` and `corporate-subs-dash-deploy`/`corporate-subs-dash-infrastructure`
* A Vite project generator
* Others?

What should the projects be named? For a minimum the typescript one should probably be prefixed with nx-

**Comment by cwoodley** [comment]
Should we prefix the package name with 'generate' to indicate it is a generator?

**Comment by JakeGinnivan** [comment]
The packages contain both generators and executors.

generator to bootstrap the library, executors do the builds/serve etc

**Comment by bennettp123** [comment]
`@wanews/typescript-project-references` &mdash; if we split this into two packages, it might make the naming easier? For example:
* `convert-nx-project-to-typescript-reference`
* `publish-package`

**Comment by JakeGinnivan** [comment]
I think maybe from a consumer point of view that may be too granular. I just realised its `@wanews/nx-typescript-project-references`. Will leave this for now
